# Generated by Django 4.2.7 on 2023-12-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_seller_review_productitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="products.product",
            ),
        ),
    ]
