# Generated by Django 4.2.7 on 2023-12-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_seller_review_productitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
    ]
