# Generated by Django 4.2.7 on 2023-12-05 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_productitem_product"),
        ("products", "0003_category_description_category_is_preferred"),
    ]

    operations = []
