# Generated by Django 4.2.7 on 2023-12-08 07:35

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to=products.models.product_image_path),
        ),
    ]
