# Generated by Django 4.2.7 on 2023-12-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_20231205_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_limited_edition',
            field=models.BooleanField(default=False),
        ),
    ]
