# Generated by Django 4.2.7 on 2023-12-08 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_productimage_image"),
        ("products", "0004_merge_20231205_0925"),
    ]

    operations = []
