# Generated by Django 4.2.7 on 2023-12-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_merge_20231208_0755'),
        ('products', '0005_product_created_at_product_updated_at'),
        ('products', '0005_product_is_limited_edition'),
    ]

    operations = [
    ]
