# Generated by Django 4.2.7 on 2023-12-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_20231218_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_daily_special',
            field=models.BooleanField(default=False),
        ),
    ]
