# Generated by Django 4.2.7 on 2023-12-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_created_at_product_updated_at'),
        ('products', '0005_product_is_limited_edition'),
        ('products', '0006_alter_productimage_product'),
    ]

    operations = [
    ]
