# Generated by Django 4.2.7 on 2023-12-27 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_20231215_1437'),
        ('products', '0007_merge_20231220_1711'),
    ]

    operations = [
    ]
