# Generated by Django 4.2.7 on 2024-01-03 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_merge_20231226_1724"),
        ("products", "0008_merge_20231229_1111"),
    ]

    operations = []
