# Generated by Django 4.2.7 on 2024-01-24 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0009_merge_20240103_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review',
                                    to='products.product'),
        ),
    ]
