# Generated by Django 4.2.7 on 2024-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0009_merge_20240103_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_method', models.CharField(
                    choices=[('PERCENT', 'Percent'), ('FIXED_AMOUNT', 'Fixed amount'), ('FIXED_PRICE', 'Fixed price')],
                    max_length=15)),
                ('value', models.PositiveIntegerField()),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')])),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('min_items', models.PositiveIntegerField(blank=True, null=True)),
                ('max_items', models.PositiveIntegerField(blank=True, null=True)),
                ('min_total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('max_total_price', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_method', models.CharField(
                    choices=[('PERCENT', 'Percent'), ('FIXED_AMOUNT', 'Fixed amount'), ('FIXED_PRICE', 'Fixed price')],
                    max_length=15)),
                ('value', models.PositiveIntegerField()),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')])),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('products', models.ManyToManyField(related_name='discounts', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_method', models.CharField(
                    choices=[('PERCENT', 'Percent'), ('FIXED_AMOUNT', 'Fixed amount'), ('FIXED_PRICE', 'Fixed price')],
                    max_length=15)),
                ('value', models.PositiveIntegerField()),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')])),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('categories', models.ManyToManyField(related_name='discounts', to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
