# Generated by Django 4.2.7 on 2024-01-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_review_product'),
        ('products', '0011_alter_review_product'),
    ]

    operations = [
    ]
